const char INDEX_HTML[] =
"<!DOCTYPE HTML>"
"<html>"
""
"<head>"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0\">"
"    <title>KTANE SETUP</title>"
"    <style>"
"        body {"
"            background-color: #101010;"
"            font-family: Arial, Helvetica, Sans-Serif;"
"            Color: #808080;"
"        }"
"    </style>"
"</head>"
""
"<body>"
"    <h1>KTANE setup</h1>"
"    <FORM action=\"/\" method=\"post\">"
"        <P>"
"            <b>Configure external features</b><br><br>"
"            Serial Number: <input type=\"text\" class=\"field left\" readonly name=\"serial_num\" id=\"serial_num\">"
"            <input type=\"button\" value=\"Generate Serial\" onclick=\"generateSerial()\">"
"            <BR>"
"            Defuse time in minutes:"
"            <select name=\"num_minutes\">"
"                <option value=\"0\">0</option>"
"                <option value=\"1\">1</option>"
"                <option value=\"2\">2</option>"
"                <option value=\"3\">3</option>"
"                <option value=\"4\">4</option>"
"                <option value=\"5\">5</option>"
"                <option value=\"6\" selected>6</option>"
"                <option value=\"7\">7</option>"
"                <option value=\"8\">8</option>"
"                <option value=\"9\">9</option>"
"            </select><BR>"
"            Number of batteries:"
"            <select name=\"num_batteries\">"
"                <option value=\"0\">0</option>"
"                <option value=\"1\">1</option>"
"                <option value=\"2\">2</option>"
"                <option value=\"3\">3</option>"
"                <option value=\"4\">4</option>"
"                <option value=\"5\">5</option>"
"                <option value=\"6\">6</option>"
"                <option value=\"7\">7</option>"
"            </select><BR>"
"            Other items: <br>"
"            <input type=\"checkbox\" name=\"port1\" value=\"port1\"> Lit FRK indicator<br>"
"            <input type=\"checkbox\" name=\"port2\" value=\"port2\"> Lit CAR indicator<br>"
"            <input type=\"checkbox\" name=\"port3\" value=\"port3\"> Parallel port<br>"
"            <input type=\"checkbox\" name=\"port4\" value=\"port4\"> RJ45 port<br>"
"            <input type=\"checkbox\" name=\"port5\" value=\"port5\"> Stereo RCA port<br>"
"            <br>"
"            <INPUT type=\"submit\" value=\"Send\"> <INPUT type=\"reset\">"
"        </P>"
"    </FORM>"
"    <script>"
"        function randomString(length, chars) {"
"            var result = '';"
"            for (var i = length; i > 0; --i) result += chars[Math.round(Math.random() * (chars.length - 1))];"
"            return result;"
"        }"
"        function generateSerial() {"
"            let serial = randomString(5, '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ');"
"            let number= Math.round(Math.random() * (9)).toString();"
"            console.log(number);"
"            serial +=number;"
"            console.log(serial);"
"            document.getElementById(\"serial_num\").value=serial;"
"        }"
"    </script>"
"</body>"
""
"</html>";